# Generated by Django 4.2.1 on 2023-06-01 14:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='body',
            field=wagtail.fields.StreamField([('about_us_hero', wagtail.blocks.StructBlock([('main_header', wagtail.blocks.CharBlock(required=True)), ('secondary_header', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], null=True, use_json_field=True),
        ),
    ]
