# Generated by Django 4.2.1 on 2023-06-01 16:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_aboutus_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=wagtail.fields.StreamField([('about_us_hero', wagtail.blocks.StructBlock([('main_header', wagtail.blocks.CharBlock(required=True)), ('secondary_header', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('secondary_header', wagtail.blocks.StructBlock([('main_header', wagtail.blocks.CharBlock(required=True)), ('main_description', wagtail.blocks.CharBlock(required=True)), ('secondary_description', wagtail.blocks.CharBlock(required=False))])), ('develop_with_us', wagtail.blocks.StructBlock([('main_header', wagtail.blocks.CharBlock(required=True)), ('elipse', wagtail.images.blocks.ImageChooserBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True))]))), ('icons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))], null=True, use_json_field=True),
        ),
    ]
