# Generated by Django 4.2.1 on 2023-06-01 17:18

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aboutus_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=wagtail.fields.StreamField([('about_us_hero', wagtail.blocks.StructBlock([('main_header', wagtail.blocks.CharBlock(required=True)), ('secondary_header', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('secondary_header', wagtail.blocks.StructBlock([('main_header', wagtail.blocks.CharBlock(required=True)), ('main_description', wagtail.blocks.CharBlock(required=True)), ('secondary_description', wagtail.blocks.CharBlock(required=False))])), ('develop_with_us', wagtail.blocks.StructBlock([('main_header', wagtail.blocks.CharBlock(required=True)), ('elipse', wagtail.images.blocks.ImageChooserBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True))]))), ('icons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('offices', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('image1', wagtail.images.blocks.ImageChooserBlock(required=False)), ('header1', wagtail.blocks.CharBlock(required=True)), ('description1', wagtail.blocks.CharBlock(required=True)), ('image2', wagtail.images.blocks.ImageChooserBlock(required=False)), ('header2', wagtail.blocks.CharBlock(required=True)), ('description2', wagtail.blocks.CharBlock(required=True)), ('image3', wagtail.images.blocks.ImageChooserBlock(required=False)), ('header3', wagtail.blocks.CharBlock(required=True)), ('description3', wagtail.blocks.CharBlock(required=True))])), ('oue_team', wagtail.blocks.StructBlock([('mini_header', wagtail.blocks.CharBlock(required=True)), ('main_header', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.CharBlock(required=True)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=True)), ('name', wagtail.blocks.CharBlock(required=True))])))]))], null=True, use_json_field=True),
        ),
    ]
