# Generated by Django 4.2.2 on 2023-06-17 20:17

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_aboutus_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootpage',
            name='body',
            field=wagtail.fields.StreamField([('root_page_hero_block', wagtail.blocks.StructBlock([('main_header', wagtail.blocks.CharBlock(label='Заголовок', required=True)), ('subtitle_header', wagtail.blocks.CharBlock(label='Текст', required=True)), ('btn_text', wagtail.blocks.CharBlock(label='Кнопка', required=False)), ('hero_image', wagtail.images.blocks.ImageChooserBlock(label='Изображение', required=True))])), ('root_page_products', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок', required=True)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Название', required=True)), ('description', wagtail.blocks.CharBlock(label='Описание', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Иконка', required=True)), ('link_page', wagtail.blocks.PageChooserBlock(label='Ссылка на страницу', required=False))]), label='Список продуктов'))])), ('root_page_clients', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])))])), ('root_page_why_choose_us', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.CharBlock(required=True))])))])), ('root_page_feature_services', wagtail.blocks.StructBlock([('main_header', wagtail.blocks.CharBlock(label='', required=True)), ('icons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True))]), label='Иконки с текстом', required=True)), ('slider', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))]), label='Ползунок', required=True))])), ('news_list', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок', required=True))])), ('faq', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.TextBlock(required=True))])))])), ('have_any_questions', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True)), ('button_subtitle', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], null=True, use_json_field=True),
        ),
    ]
