# Generated by Django 4.2.1 on 2023-06-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_qazcloudmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
