# Generated by Django 4.2.2 on 2023-06-18 19:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cloudmigration_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudmigration',
            name='body',
            field=wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('hero_title', wagtail.blocks.CharBlock(required=True)), ('hero_subtitle', wagtail.blocks.CharBlock(required=True)), ('hero_image', wagtail.images.blocks.ImageChooserBlock())])), ('faq', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.TextBlock(required=True))])))])), ('news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок', required=True))])), ('floating_block', wagtail.blocks.StructBlock([('context', wagtail.blocks.CharBlock(required=True)), ('js_link', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(required=True)))])), ('have_any_questions', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True)), ('button_subtitle', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('cloud_migration_fast_and_safe', wagtail.blocks.StructBlock([('little_header', wagtail.blocks.CharBlock(required=True)), ('main_header', wagtail.blocks.CharBlock(required=True)), ('paragraph1', wagtail.blocks.CharBlock(required=True)), ('paragraph2', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('to_pereezd', wagtail.blocks.StructBlock([('little_header', wagtail.blocks.CharBlock(required=True)), ('main_header', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('repo_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('body', wagtail.blocks.CharBlock(required=True))])))])), ('cloud_migration_benefits', wagtail.blocks.StructBlock([('little_header', wagtail.blocks.CharBlock(required=True)), ('main_header', wagtail.blocks.CharBlock(required=True)), ('paragraph', wagtail.blocks.CharBlock(required=True)), ('icons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(required=True))])))])), ('video_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True)), ('iframe', wagtail.blocks.URLBlock(required=True))]))], null=True, use_json_field=True),
        ),
    ]
